### ISSUE TITLE
Missing notebooks

### ISSUE THREAD

**Issue by satulovsky** [mehak25/BiGAN#2]
> ===============================Data Preprocessing=========================
Run **data_preporcessAir.ipynb** for preprocessing AirQuality data Run **data_preporcessMimic.ipynb** for preprocessing AirQuality data All data preprocessed files are in data folder. AirQuality- data->air->preprocess MIMIC- data->mimic->preprocess

None of the notebooks mentioned seems to be in the repository, could you provide them, please?

**Comment by mehak25** [comment]
preprocess notebooks and files are updated in data/air/preprocess and data/mimic/preprocess folders.

**Comment by satulovsky** [comment]
Thank you so much for uploading them, Mehak! 
Much appreciated.

Best,
Javier
